#!/usr/bin/env python3
"""Plot Crazyflie variable logs produced by the driver CSV logger.

Usage:
    python plot_crazyflie_variable_log.py /path/to/XX.csv
    python plot_crazyflie_variable_log.py /path/to/XX.csv --save plot.png
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Dict, List

import matplotlib.pyplot as plt


def load_log(csv_path: Path) -> tuple[List[float], Dict[str, List[float]]]:
    with csv_path.open("r", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        if reader.fieldnames is None:
            raise RuntimeError("CSV file has no header")

        if "timestamp" not in reader.fieldnames:
            raise RuntimeError("CSV file must contain a 'timestamp' column")

        variable_names = [name for name in reader.fieldnames if name != "timestamp"]
        if not variable_names:
            raise RuntimeError("CSV file has no variable columns to plot")

        timestamps: List[float] = []
        values: Dict[str, List[float]] = {name: [] for name in variable_names}

        for row in reader:
            try:
                ts = float(row["timestamp"])
            except (TypeError, ValueError):
                continue

            numeric_row: Dict[str, float] = {}
            skip_row = False
            for name in variable_names:
                try:
                    numeric_row[name] = float(row[name])
                except (TypeError, ValueError):
                    skip_row = True
                    break

            if skip_row:
                continue

            timestamps.append(ts)
            for name in variable_names:
                values[name].append(numeric_row[name])

    if not timestamps:
        raise RuntimeError("No valid numeric rows found in CSV file")

    t0 = timestamps[0]
    time_axis = [t - t0 for t in timestamps]
    return time_axis, values


def plot_log(time_axis: List[float], values: Dict[str, List[float]], *, title: str) -> None:
    fig, ax = plt.subplots(figsize=(12, 6))

    for name, series in values.items():
        ax.plot(time_axis, series, label=name, linewidth=1.5)

    ax.set_title(title)
    ax.set_xlabel("Time [s]")
    ax.set_ylabel("Value")
    ax.grid(True, alpha=0.3)
    ax.legend()
    fig.tight_layout()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot Crazyflie variable log CSV generated by the driver"
    )
    parser.add_argument("csv", type=Path, help="Path to a Crazyflie CSV log file")
    parser.add_argument(
        "--save",
        type=Path,
        default=None,
        help="Optional output image path (e.g. plot.png). If omitted, opens a window.",
    )
    parser.add_argument(
        "--title",
        type=str,
        default="Crazyflie Variable Log",
        help="Plot title",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if not args.csv.exists():
        raise SystemExit(f"CSV file not found: {args.csv}")

    time_axis, values = load_log(args.csv)
    plot_log(time_axis, values, title=args.title)

    if args.save is not None:
        args.save.parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(args.save, dpi=150)
        print(f"Saved plot to {args.save}")
    else:
        plt.show()


if __name__ == "__main__":
    main()
