[tool.poetry]
name = "flockwave-server"
version = "1.16.0"
description = "Skybrush server component"
authors = ["Tamas Nepusz <tamas@collmot.com>", "Gabor Vasarhelyi <vasarhelyi@collmot.com>"]
packages = [
    { include = "flockwave", from = "src" },
    { include = "skybrush", from = "src" }
]

[[tool.poetry.source]]
name = "collmot"
url = "https://pypi.collmot.com/simple/"

[tool.poetry.dependencies]
python = "^3.7"
bidict = "^0.19.0"
click = "^7.1.2"
blinker = "^1.4"
jsonschema = "^3.2.0"
python-baseconv = "^1.2.2"
pynmea2 = "^1.15.0"
zeroconf = "^0.28.0"
pymavlink = "^2.4.9"
trio = "^0.17.0"
quart = "^0.12.0"
quart-trio = "^0.5.1"
trio-util = ">=0.2.0"
sentry-sdk = "^0.19.0"
python-dotenv = "^0.14.0"
multidict = "^4.7.6"
colour = "^0.1.5"
pyjwt = "^1.7.1"
paramiko = "^2.7.1"
scp = "^0.13.2"
hypercorn = {extras = ["trio"], version = "^0.10.1"}
tinyrpc = {version = ">=1.0.4", extras = ["msgpack"]}
passlib = {extras = ["bcrypt"], version = "^1.7.2"}
flockwave-conn = {extras = ["midi", "rpc", "serial"], version = "^2.9.1"}
flockwave-ext = "^1.5.0"
flockwave-flockctrl = "^0.14.0"
flockwave-gps = "^1.4.0"
flockwave-logger = "^1.6.0"
flockwave-parsers = "^1.2.0"
flockwave-spec = "^1.46.0"
pyledctrl = "^3.1.0"
aiocflib = "^1.2.0"
appdirs = "^1.4.4"
crcmod = "^1.7"
flockwave-app-framework = {version = "^1.2.0", extras = ["daemon"]}
msgpack = "^1.0.0"
aio-usb-hotplug = "^3.0.1"
pyserial = "^3.4"
compose = "^1.1.1"
diskcache = "^5.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
pytest-trio = "^0.6.0"
click-man = "^0.4.1"
black = {version = "^20.8b1", allow-prereleases = true}
pyinstaller = {version = "^4.0", extras = ["encryption"]}
pyarmor = "^6.6.0"
pynsist = "^2.7"

[tool.poetry.scripts]
skybrushd = "flockwave.server.launcher:start"
skybrush-gateway = "flockwave.gateway.launcher:start"
skybrush-proxy = "flockwave.proxy.launcher:start"
