name: flockwave-server
version: git
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel
confinement: devmode

parts:
  python37:
    source: https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tar.xz
    source-type: tar
    source-checksum: md5/93df27aec0cd18d6d42173e601ffbbfd
    plugin: autotools
    configflags:
      - --prefix=/usr
    build-packages:
      - libbz2-dev
      - libexpat1-dev
      - libffi-dev
      - libgdbm-dev
      - liblzma-dev
      - libncurses5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libzip-dev
      - uuid-dev
    stage-packages:
      - libbz2-1.0
      - libexpat1
      - libffi6
      - libgdbm3
      - liblzma5
      - libncurses5
      - libreadline6
      - libsqlite3-0
      - libssl1.0.0
      - libzip4
      - uuid-runtime
    stage:
      - -usr/lib/python3.7/test
      - -var

  snapcraft-preload:
    source: https://github.com/diddlesnaps/snapcraft-preload.git
    source-branch: semaphore-support
    plugin: cmake
    build-packages:
      - on amd64:
        - gcc-multilib
        - g++-multilib

  flockwave-server:
    plugin: python
    source: .
    requirements: ./requirements.txt
    after:
      - python37
    build-packages:
      - g++
      - libxml2-dev
      - libxslt-dev
    stage-packages:
      - libxml2
      - libxslt1.1
    stage:
      - -usr/bin/2to3
      - -usr/bin/pydoc3
      - -usr/bin/python3
    override-pull: |
      cat <<EOF >~/.netrc
      machine git.collmot.com
        login tamas
        password b68ade0bb1ec8480aa19adc7d302c3789d7133ac
      EOF
      snapcraftctl pull
    override-prime: |
      snapcraftctl prime
      rm ~/.netrc

  flockwave-server-config:
    plugin: dump
    source: .
    stage:
      - etc/envs/snap.cfg

apps:
  flockwaved:
    command: bin/snapcraft-preload $SNAP/bin/flockwaved -c $SNAP/etc/envs/snap.cfg
    daemon: simple

slots:
  dock:
    interface: content
    content: socket-directory
    write:
      - $SNAP_COMMON
